# Generated by Django 5.1.5 on 2025-02-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
